# dashboard/app.py
import streamlit as st

st.set_page_config(
    page_title="Trading Bot Dashboard",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Trading Bot Dashboard")
st.markdown("---")

col1, col2, col3 = st.columns(3)

col1.info("📊 **Market Data**\nView live OHLCV charts and price action.")
col2.info("🚦 **Signals**\nMonitor BUY/SELL signals generated by the bot.")
col3.info("🔬 **Backtest**\nAnalyze historical backtest performance.")

st.markdown("---")
st.markdown("Use the **sidebar** to navigate between pages.")
